openapi: 3.0.0
info:
  title: HOME 관련 API
  version: 1.0.0

paths:
  /home:
    post:
      summary: "랜덤 여행지 추천"
      tags:
        - HOME
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                departure:
                  type: string
                  description: "출발지"
                  example: 부산
                transportType:
                  type: string
                  description: "이동 수단"
                  example: 자가용
                startDate:
                  type: string
                  format: date-time
                  description: "여행 시작 날짜"
                  example: "2025-01-06T12:00:00Z"
                endDate:
                  type: string
                  format: date-time
                  description: "여행 종료 날짜"
                  example: "2025-01-08T12:00:00Z"
                participants:
                  type: integer
                  description: "여행 인원"
                  example: 5
                timeZone:
                  type: string
                  description: "이동 시간대"
                  example: 2
      responses:
        '200':
          description: "랜덤 여행지 추천 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "랜덤 여행지 추천 성공"
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        parentRegion:
                          type: string
                          description: "부모 지역"
                          example: "경상북도"
                        childRegion:
                          type: string
                          description: "자식 지역"
                          example: "대구"
                        travelTime:
                          type: string
                          description: "여행 시간"
                          example: "1시간 44분"
                    example:
                      - parentRegion: "경상북도"
                        childRegion: "대구"
                        travelTime: "1시간 44분"
                      - parentRegion: "충청남도"
                        childRegion: "천안"
                        travelTime: "1시간 11분"
                      - parentRegion: "충청북도"
                        childRegion: "충주"
                        travelTime: "1시간 30분"
                  departure:
                    type: string
                    description: "출발지"
                    example: "부산"
                  transportType:
                    type: string
                    description: "이동 수단"
                    example: "자가용"
                  startDate:
                    type: string
                    format: date-time
                    description: "여행 시작 날짜"
                    example: "2025-01-06T12:00:00Z"
                  endDate:
                    type: string
                    format: date-time
                    description: "여행 종료 날짜"
                    example: "2025-01-08T12:00:00Z"
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."

