openapi: 3.0.0
info:
  title: HOME 관련 API
  version: 1.0.0

paths:
  /home:
    post:
      summary: "랜덤 여행지 추천"
      tags:
        - HOME
      requestBody:
        description: "duration 값: 1, 1-2, 2-3, 3+ 중 하나"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                departure:
                  type: string
                  description: "출발지 (예: 부산)"
                  example: "부산"
                participants:
                  type: integer
                  description: "여행 인원 (예: 5)"
                  example: 5
                vehicle:
                  type: string
                  description: "이동 수단 (예: 자가용)"
                  example: "자가용"
                duration:
                  type: string
                  description: |
                    여행 시간 (가능한 값: '1', '1-2', '2-3', '3+')
                  enum:
                    - "1"
                    - "1-2"
                    - "2-3"
                    - "3+"
                  example: "2-3"
                startDate:
                  type: string
                  format: date-time
                  description: "여행 시작 날짜 (예: 2025-01-06T12:00:00Z)"
                  example: "2025-01-06T12:00:00Z"
                endDate:
                  type: string
                  format: date-time
                  description: "여행 종료 날짜 (예: 2025-01-08T12:00:00Z)"
                  example: "2025-01-08T12:00:00Z"
      responses:
        '200':
          description: "랜덤 여행지 추천 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "랜덤 여행지 추천 성공"
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        location:
                          type: string
                          description: "자식 지역"
                          example: "대구"
                        region:
                          type: string
                          description: "부모 지역"
                          example: "경상북도"
                    example:
                      - region: "경상북도"
                        location: "대구"
                        growthRate: -3.2
                      - region: "충청남도"
                        location: "천안"
                        growthRate: 2.5
                      - region: "충청북도"
                        location: "충주"
                        growthRate: -7.2
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "잘못된 요청입니다."
  
  /home/save-trip:
    post:
      summary: "여행 일정 등록"
      tags:
        - HOME
      requestBody:
        description: "duration 값: 1, 1-2, 2-3, 3+ 중 하나"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                  description: "여행 지역"
                  example: "부산"
                participants:
                  type: integer
                  description: "여행 인원"
                  example: 5
                vehicle:
                  type: string
                  description: "이동 수단"
                  example: "자가용"
                duration:
                  type: string
                  description: |
                    여행 시간 (가능한 값: '1', '1-2', '2-3', '3+')
                  example: "2-3"
                startDate:
                  type: string
                  format: date-time
                  description: "여행 시작 날짜"
                  example: "2025-01-06T12:00:00Z"
                endDate:
                  type: string
                  format: date-time
                  description: "여행 종료 날짜"
                  example: "2025-01-08T12:00:00Z"
      responses:
        '200':
          description: "여행 일정 등록 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "여행 일정이 성공적으로 등록되었습니다."
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."

  /home/popular-missions:
    get:
      summary: "인기 미션 조회"
      tags:
        - HOME
      responses:
        '200':
          description: "인기 미션 조회 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "인기 미션 조회 성공"
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        missionId:
                          type: int
                          description: "미션 id"
                          example: 1
                        region:
                          type: string
                          description: "지역명"
                          example: "순천"
                        missionTitle:
                          type: string
                          description: "미션 제목"
                          example: "길 고양이 사진 찍기"
                    example:
                      - missionId : 2
                        region: "순천"
                        missionTitle: "길 고양이 사진 찍기"
                      - missionId : 3
                        region: "순천"
                        missionTitle: "길 고양이 사진 찍기"
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."

  /home/upcoming-trips:
    get:
      summary: "다가오는 여행 조회"
      tags:
        - HOME
      parameters:
        - name: userId
          in: query
          required: true
          description: "사용자의 ID"
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: "다가오는 여행 조회 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "다가오는 여행 조회 성공"
                  result:
                    type: object
                    properties:
                      tripId:
                        type: int
                        description: "여행 id"
                        example: 1
                      location:
                        type: string
                        description: "여행 지역"
                        example: "부산"
                      participants:
                        type: integer
                        description: "여행 인원"
                        example: 5
                      vehicle:
                        type: string
                        description: "이동 수단"
                        example: "자가용"
                      duration:
                        type: string
                        description: |
                          여행 시간 (가능한 값: '1', '1-2', '2-3', '3+')
                        example: "2-3"
                      startDate:
                        type: string
                        format: date-time
                        description: "여행 시작 날짜"
                        example: "2025-01-06T12:00:00Z"
                      endDate:
                        type: string
                        format: date-time
                        description: "여행 종료 날짜"
                        example: "2025-01-08T12:00:00Z"
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."

  /home/upcoming-trips/{tripId}:
    delete:
      summary: "다가오는 여행 삭제"
      tags:
        - HOME
      parameters:
        - name: tripId
          in: path
          required: true
          description: "삭제할 여행의 ID"
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: "여행 삭제 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "여행이 성공적으로 삭제되었습니다."
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."
        '404':
          description: "해당 여행을 찾을 수 없음"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "해당 여행을 찾을 수 없습니다."