openapi: 3.0.0
info:
  title: USER 관련 API
  version: 1.0.0
paths:
  /users/info:
    get:
      tags:
        - USER
      summary: 마이페이지 정보 조회
      responses:
        "200":
          description: 마이페이지 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 마이페이지 정보 조회 성공
                  result:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        example: 1
                      email:
                        type: string
                        example: test@example.com
                      nickname:
                        type: string
                        example: tndbsrkd
                      profile_image:
                        type: string
                        example: "https://example.com/images/profile.jpg"
                      point:
                        type: integer
                        example: 1400
                      temperature:
                        type: integer
                        example: 30
                      travelCount:
                        type: integer
                        example: 1
                      completedMissions:
                        type: integer
                        example: 8
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 잘못된 요청입니다.
  /users/profile:
    patch:
      tags:
        - USER
      summary: 프로필 수정
      requestBody:
        description: "수정할 프로필 데이터(이미지, 이메일, 닉네임 중 하나 이상)"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  description: "변경할 닉네임"
                  example: "newNickname"
                email:
                  type: string
                  description: "변경할 이메일"
                  example: "newEmail@example.com"
                profileImage:
                  format: uri
                  description: "프로필 이미지"
                  example: "https://example.com/images/profile.jpg"
      responses:
        "200":
          description: 프로필 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "프로필이 성공적으로 업데이트되었습니다."
        "409":
          description: 이미 존재하는 닉네임 혹은 이메일
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 409
                  message:
                    type: string
                    example: "이미 존재하는 닉네임입니다."
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."
  /users/past-trips:
    get:
      tags:
        - USER
      summary: 지난 여행 조회
      responses:
        "200":
          description: 지난 여행 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 지난 여행 목록 조회 성공
                  result:
                    type: object
                    properties:
                      pastTrips:
                        type: array
                        items:
                          type: object
                          properties:
                            tripId:
                              type: integer
                              example: 1
                            location:
                              type: string
                              example: 충주
                            adult_participants:
                              type: integer
                              description: "여행 어른 인원 (예: 5)"
                              example: 5
                            child_participants:
                              type: integer
                              description: "여행 아이 인원 (예: 2)"
                              example: 2
                            vehicle:
                              type: string
                              example: 자가용
                            startDate:
                              type: string
                              format: date-time
                              example: "2025-01-22T00:00:00+09:00"
                            endDate:
                              type: string
                              format: date-time
                              example: "2025-01-24T00:00:00+09:00"
                            missions:
                              type: array
                              items:
                                type: object
                                properties:
                                  mission:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                        example: 1
                                      title:
                                        type: string
                                        example: 명소 인증샷 찍기
                                      imageUrl:
                                        type: string
                                        example: "https://example.com/images/landmark-photo.jpg"
                                      content:
                                        type: string
                                        example: 여행지의 유명한 명소를 배경으로 사진을 찍어 인증하세요.
                                      point:
                                        type: integer
                                        example: 100
                                  receivedMission:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                        example: 2
                                      content:
                                        type: string
                                        example: 명소 인증샷 미션 완료
                                      status:
                                        type: boolean
                                        example: true
                                      createdAt:
                                        type: string
                                        format: date-time
                                        example: "2024-11-26T12:00:00Z"
                                      updatedAt:
                                        type: string
                                        format: date-time
                                        example: "2024-11-26T12:00:00Z"
                                      imgUrl:
                                        type: string
                                        description: 미션 인증 사진
                                        example: https://example.com/mission_5.jpg
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 잘못된 요청입니다.

  /users/past-trips/{tripId}:
    delete:
      summary: "지난 여행 삭제"
      tags:
        - USER
      parameters:
        - name: tripId
          in: path
          required: true
          description: "삭제할 지난 여행의 ID"
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: "지난 여행 일정 삭제 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "지난 여행 일정이 성공적으로 삭제되었습니다."
        '400':
          description: "잘못된 요청"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "잘못된 요청입니다."
        '404':
          description: "해당 여행을 찾을 수 없음"
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "해당 여행을 찾을 수 없습니다."

  /users/my-missions:
    get:
      tags:
        - USER
      summary: 저장한 미션 조회
      responses:
        "200":
          description: 저장한 미션 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 저장한 미션 조회 성공
                  result:
                    type: object
                    properties:
                      missions:
                        type: array
                        items:
                          type: object
                          properties:
                            tripId:
                              type: integer
                              example: 1
                            missionId:
                              type: integer
                              example: 4
                            imageUrl:
                              type: string
                              example: https://example.com/images/nature-walk.jpg
                            title:
                              type: string
                              example: 자연 속 산책
                            point:
                              type: integer
                              example: 30
                        example:
                        - tripId: 12
                          missionId: 2
                          imageUrl: https://example.com/images/landmark-photo.jpg
                          title: 명소 인증샷 찍기
                          point: 100
                        - tripId: 12
                          missionId: 5
                          imageUrl: https://example.com/images/souvenir.jpg
                          title: 기념품 구입
                          point: 70
                        - tripId: 12
                          missionId: 2
                          imageUrl: https://example.com/images/landmark-photo.jpg
                          title: 명소 인증샷 찍기
                          point: 100
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 잘못된 요청입니다.
        "500":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: 저장한 미션 조회 중 서버 오류 발생.


  /users/past-trips/{tripId}/{missionId}:
    get:
      tags:
        - USER
      summary: 미션 상세 조회
      description: "mission_id: 미션 자체의 id, receive_mission_id: 사용자가 저장한 미션 id, status: 미션 인증 여부"
      parameters:
        - name: tripId
          in: path
          required: true
          schema:
            type: integer
            example: 1
        - name: missionId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: 미션 상세 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 미션 상세 조회 성공
                  result:
                    type: object
                    properties:
                      tripId:
                        type: integer
                        example: 1
                      missionId:
                        type: integer
                        example: 1
                      receive_mission_id:
                        type: integer
                        example: 13
                      content:
                        type: string
                        example: "명소 인증샷 미션 완료"
                      picture:
                        type: string
                        example: "https://example.com/images/mission1.jpg"
                      status:
                        type: boolean
                        example: true
                      createdAt:
                        type: string
                        format: date-time
                        example: "2024-11-26T12:00:00Z"
                      updatedAt:
                        type: string
                        format: date-time
                        example: "2024-11-26T12:00:00Z"
                      imgUrl:
                        type: string
                        example: https://example.com/mission_14.jpg
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 잘못된 요청입니다.

  /users/my-posts:
    get:
      tags:
        - USER
      summary: 내가 쓴 글 조회
      responses:
        "200":
          description: 내가 쓴 글 목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 내가 쓴 글 목록 조회 성공
                  result:
                    type: object
                    properties:
                      posts:
                        type: array
                        items:
                          type: object
                          properties:
                            postId:
                              type: integer
                              example: 1
                            categoryId:
                              type: integer
                              example: 1
                            userId:
                              type: integer
                              example: 1
                            localId:
                              type: integer
                              example: 1
                            title:
                              type: string
                              example: 현지 맛집 정보
                            content:
                              type: string
                              example: 여기에서 꼭 가봐야 할 숨겨진 맛집 리스트입니다.
                            pictureUrl:
                              type: string
                              example: "https://example.com/images/mission1.jpg"
                            createdAt:
                              type: string
                              format: date-time
                              example: "2024-11-26T12:00:00Z"
                            updatedAt:
                              type: string
                              format: date-time
                              example: "2024-11-26T12:00:00Z"
                            likeCount:
                              type: integer
                              example: 5
                            scrapCount:
                              type: integer
                              example: 0
                            commentCount:
                              type: integer
                              example: 3
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 잘못된 요청입니다.