name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host wego
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh wego 'sudo mkdir -p /opt/app'
          ssh wego 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* wego:/opt/app

      - name: Create .env file on EC2
        run: |
          ssh wego '
            echo "PORT=3000" >> /opt/app/.env
            printf "JWT_PRIVATE_KEY=\"${{ secrets.JWT_PRIVATE_KEY }}\"" > /opt/app/.env
            printf "JWT_PUBLIC_KEY=\"${{ secrets.JWT_PUBLIC_KEY }}\"" >> /opt/app/.env
            echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> /opt/app/.env
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> /opt/app/.env

            echo "DB_HOST=${{ secrets.DB_HOST }}" >> /opt/app/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> /opt/app/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /opt/app/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> /opt/app/.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> /opt/app/.env
          '

      - name: Install dependencies
        run: |
          ssh wego 'npm install --prefix /opt/app/'

      - name: Copy systemd service file
        run: |
          ssh wego '
            echo "[Unit]
            Description=UMC WEGO Project
            After=network.target

            [Service]
            User=${USER}
            EnvironmentFile=/opt/app/.env
            ExecStart=/usr/bin/npm run dev --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh wego 'sudo systemctl daemon-reload'
          ssh wego 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh wego 'sudo systemctl restart app'
